apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: root
      admin_password: secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  parentRefs:
  - name: shared-gateway
    namespace: gateway
  hostnames:
  - "grafana.lab.sturla.tech"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: grafana-service
          port: 3000
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
spec:
  name: loki.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-query-frontend:3100
      isDefault: true
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
        maxLines: 1000
      secureJsonData:
        httpHeaderValue1: "admin"
