apiVersion: kustomize.config.k8s.io/v1beta1

namespace: nextcloud
resources:
- namespace.yaml
- postgres.yaml
- http-routes.yaml

helmCharts:
- name: nextcloud
  version: 6.6.10
  repo: https://nextcloud.github.io/helm/
  releaseName: nextcloud
  valuesFile: values.yaml
