apiVersion: kustomize.config.k8s.io/v1beta1

namespace: vcluster
resources:
- namespace.yaml

helmCharts:
- name: vcluster
  version: 0.25.0
  repo: https://charts.loft.sh
  releaseName: vcluster
  valuesFile: values.yaml
