apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: &email robertsturla@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-private-key   # Stores the ACME account private key
    solvers:
      - dns01:
          cloudflare:
            email: *email
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-dns
spec:
  acme:
    email: &email robertsturla@outlook.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-staging-private-key
    solvers:
      - dns01:
          cloudflare:
            email: *email
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
