apiVersion: kustomize.config.k8s.io/v1beta1

namespace: forgejo
resources:
  - namespace.yaml
  - postgres.yaml
  - http-routes.yaml

helmCharts:
  - name: forgejo
    version: 12.5.4
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo
    valuesFile: values.yaml
    namespace: forgejo
