gitea:
  config:
    server:
      ROOT_URL: "https://git.lab.sturla.tech"
      DOMAIN: "git.lab.sturla.tech"
      HTTP_PORT: 3000
      SSH_PORT: 22
      OFFLINE_MODE: true
    repository:
      ROOT: /data/git/repositories
    repository.pull-request:
      WORK_IN_PROGRESS_PREFIXES: "WIP:,[WIP]:"
    lfs:
      PATH: /data/git/lfs
    database:
      DB_TYPE: postgres
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__HOST
      valueFrom:
        secretKeyRef:
          name: forgejo-db-app
          key: host
    - name: FORGEJO__DATABASE__NAME
      valueFrom:
        secretKeyRef:
          name: forgejo-db-app
          key: dbname
    - name: FORGEJO__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: forgejo-db-app
          key: username
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-db-app
          key: password

postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false

redis-cluster:
  enabled: false
redis:
  enabled: true

replicaCount: 1
namespaceOverride: forgejo
