apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argo-rollouts
resources:
- namespace.yaml

helmCharts:
- name: argo-rollouts
  version: 2.40.3
  repo: https://argoproj.github.io/argo-helm
  releaseName: argo-rollouts
