apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cnpg-system
resources:
- namespace.yaml

helmCharts:
- name: cloudnative-pg
  version: v0.23.2
  repo: https://cloudnative-pg.github.io/charts
  releaseName: cnpg
  valuesFile: values.yaml
