apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cnpg-system
resources:
- namespace.yaml
- cluster.yaml

helmCharts:
- name: cloudnative-pg
  version: 0.24.0
  repo: https://cloudnative-pg.github.io/charts
  releaseName: cnpg
  valuesFile: values.yaml

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
