apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd
resources:
- namespace.yaml
- http-routes.yaml

helmCharts:
- name: argo-cd
  version: 8.0.9
  repo: https://argoproj.github.io/argo-helm
  releaseName: argocd
  valuesFile: values.yaml
