apiVersion: kustomize.config.k8s.io/v1beta1

namespace: coder
resources:
- namespace.yaml
- postgres.yaml
- http-routes.yaml

helmCharts:
- name: coder
  version: 2.23.1
  repo: https://helm.coder.com/v2
  releaseName: coder-v2
  valuesFile: values.yaml
