apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator

resources:
- namespace.yaml
- https://github.com/grafana/grafana-operator/releases/download/v5.18.0/crds.yaml

helmCharts:
- name: grafana-operator
  version: 5.18.0
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana-operator
  valuesFile: values.yaml
  namespace: grafana-operator

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
