apiVersion: kustomize.config.k8s.io/v1beta1

namespace: reloader
resources:
- namespace.yaml

helmCharts:
- name: reloader
  version: 2.1.3
  repo: https://stakater.github.io/stakater-charts
  releaseName: reloader
  valuesFile: values.yaml
