apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: awx
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
  - cr.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1
