gitea:
  config:
    APP_NAME: "Forgejo: Git with a cup of tea"
    repository:
      ROOT: "~/gitea-repositories"
    repository.pull-request:
      WORK_IN_PROGRESS_PREFIXES: "WIP:,[WIP]:"
    database:
      DB_TYPE: postgres
      HOST: forgejo-db-rw
      NAME: forgejo
      USER:
      PASSWD:

postgresql:
  enabled: false

replicaCount: 1
