apiVersion: kustomize.config.k8s.io/v1beta1

namespace: authentik
resources:
- namespace.yaml
- postgres.yaml
- secret.yaml
- http-routes.yaml

helmCharts:
- name: authentik
  version: 2025.6.0
  repo: https://charts.goauthentik.io
  releaseName: authentik
  valuesFile: values.yaml
