---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secret-key-gen
spec:
  length: 50
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  target:
    name: secret-key
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-secret-key-gen
