authentik:
  email:
  secret_key: file:///authentik-secret/secret-key
  postgresql:
    host: file:///postgres-creds/host
    name: file:///postgres-creds/dbname
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
    port: 5432

server:
  ingress:
    enabled: false
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-db-app
    - name: authentik-secret
      secret:
        secretName: authentik-secret-key
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-secret
      mountPath: /authentik-secret
      readOnly: true

worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-db-app
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

postgresql:
  enabled: false

redis:
  enabled: true