authentik:
  email:
  secret_key: "PleaseGenerateA50CharKey"
  postgresql:
    host: file:///postgres-creds/host
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
    port: 5432

server:
  ingress:
    enabled: false
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-db-app
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-db-app
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

postgresql:
  enabled: false

redis:
  enabled: true