apiVersion: kustomize.config.k8s.io/v1beta1

namespace: external-secrets
resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  version: 0.17.0
  repo: https://charts.external-secrets.io
  releaseName: external-secrets
  valuesFile: values.yaml
