apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argo-workflows
resources:
- namespace.yaml

helmCharts:
- name: argo-workflows
  version: 0.45.13
  repo: https://argoproj.github.io/argo-helm
  releaseName: argo-workflows
  valuesFile: values.yaml
