apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.6.7/install.yaml
