apiVersion: kustomize.config.k8s.io/v1beta1

# namespace: monitoring
resources:
- http-routes.yaml

helmCharts:
- name: loki
  version: 6.30.1
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  valuesFile: values.yaml
  namespace: monitoring
