apiVersion: kustomize.config.k8s.io/v1beta1

helmCharts:
- name: loki
  version: 6.30.1
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  valuesFile: values.yaml
  namespace: monitoring
