---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-https
spec:
  parentRefs:
  - name: shared-gateway
    namespace: gateway
  hostnames:
  - "argocd.sturla.tech"
  rules:
  - backendRefs:
    - name: argo-server
      port: 443
