global:
  domain: argocd.lab.sturla.tech

configs:
  cm:
    '"kustomize.buildOptions"': --enable-helm
    '"application.resourceTrackingMethod"': "annotation"
    '"resource.customizations.ignoreResourceUpdates.all"': |
      jsonPointers:
        - /spec/preserveUnknownFields
  params:
    # Required for TLS termination on the Gateway
    server.insecure: true
